// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxkmljsviyuwrvxabjln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4a21sanN2aXl1d3J2eGFiamxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjk5MzMsImV4cCI6MjA1OTkwNTkzM30.8fUFy3ZRG1bXbiqCVP_Up5mHdd_VzFJrds0-RUZHkOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);